name: Deploy Pelican Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown ghp-import

      - name: Build the site
        run: pelican content -o output -s publishconf.py

      - name: Post-process HTML
        run: |
          # Например, заменим или добавим что-то в HTML файлы
          find output -name "*.html" -exec sed -i 's|<link href="/theme/css/style.css" rel="stylesheet" type="text/css" media="screen" />|<link href="theme/css/style.css" rel="stylesheet" type="text/css" media="screen" />|g' {} \;

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p output
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
