name: Deploy Pelican Site to GitHub Pages

on:
  push:
    branches:
      - main  # Запуск действия при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    # 2. Устанавливаем зависимости (опционально)
    - name: Install dependencies
      run: |
        npm install  # Замените на команду для вашего проекта

    # 3. Собираем проект
    - name: Build project
      run: |
        npm run build  # Замените на команду сборки
        mv ./output ./public  # Например, если папка сборки называется иначе

    # 4. Деплоим содержимое папки output в ветку gh-pages
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./output  # Путь к папке, которая будет опубликована
        destination_branch: gh-pages
        id: deployment
        uses: actions/deploy-pages@v4
